language: python
python: "3.7"
before_install:
  - python --version
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install awscli
  - export PATH=$PATH:$HOME/.local/bin
script:
  - mkdocs build -d output
deploy:
  - provider: script
    script: aws s3 rm s3://rezepte.vogt4nick.com --recursive --region=us-east-1
    skip_cleanup: true
    on:
      branch: rezepte.vogt4nick.com
  - provider: s3
    bucket: rezepte.vogt4nick.com
    skip_cleanup: true
    region: us-east-1
    local_dir: output
    default_text_charset: utf-8
    cache_control: no-cache
    acl: public_read
    on:
      branch: rezepte.vogt4nick.com
