docs_dir: src
extra_css:
  - assets/stylesheets/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
plugins:
  - awesome-pages:
      collapse_single_pages: false
      filename: pages.yml
      strict: true
  - git-revision-date-localized:
      enable_creation_date: true
      locale: de
      type: timeago
      timezone: Europe/Vienna
  - macros
  - minify:
      minify_html: true
      minify_css: true
      css_files:
        - assets/stylesheets/extra.css
  - search:
      lang:
        - de
site_name: dem Nick seine Rezepte
site_url: http://rezepte.vogt4nick.com/
theme:
  name: material
  favicon: assets/images/shallow-pan-of-food-32x32.png
  features:
    - header.autohide
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - toc.integrate
  icon:
    logo: material/silverware
  language: de
  palette:
    primary: red
    accent: red
  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true
