name: &NAME Update Build Dependencies
on:
  schedule:
    - cron: "0 0 * * FRI"
  push: # for testing

env:
  MKDOCS_SITE_DIR: ~/site

jobs:
  update_dependencies:
    name: *NAME
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: Gr1N/setup-poetry@v7
        with:
          poetry-version: 1.1.11
      - name: *NAME
        run: poetry update
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
